# Generated by Django 3.1.3 on 2024-03-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
